# Generated by Django 3.2.3 on 2022-06-30 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Marka produktu',
                'verbose_name_plural': 'Marka produktów',
            },
        ),
        migrations.CreateModel(
            name='CategoryClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50)),
                ('category_image', models.ImageField(blank=True, upload_to='category/')),
                ('category_slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('text', models.TextField(verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Cena')),
                ('from_state', models.CharField(max_length=100, verbose_name='Województwo')),
                ('from_city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('publication_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.categoryclass')),
            ],
            options={
                'verbose_name': 'Produkt Bazowy',
                'verbose_name_plural': 'Produkty bazowe',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image01', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image02', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image03', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image04', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image05', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image06', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image07', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image08', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image09', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productbase')),
            ],
            options={
                'verbose_name': 'Zdjęcia produktu',
                'verbose_name_plural': 'Zdjęcia produktów',
            },
        ),
    ]
