# Generated by Django 3.2.3 on 2022-06-30 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='prvMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=200)),
                ('sendDate', models.DateTimeField(auto_now_add=True)),
                ('reciver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_kogo', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_kogo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
