# Generated by Django 3.2.3 on 2022-07-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privmsg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prvmsg',
            name='title',
            field=models.TextField(default='masowy wpis', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prvmsg',
            name='msg',
            field=models.TextField(max_length=1000),
        ),
    ]
